language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
env:
  global:
    - DATABASE_URL=test
git:
  autocrlf:
    - 'input'
before_script:
  - npm install make-coverage-badge
script:
  - npm test
after_script:
  - make-coverage-badge --output-path ./badges
notifications:
  email: false
